global:
  default_provider: "deepseek"

providers:
  deepseek:
    api_key: "test-deepseek-key"
    base_url: "https://api.deepseek.com"

features:
  meaning_formatter:
    multi_char:
      provider: "deepseek"
      model: "deepseek-chat"
      prompt: "ai_config/prompts/meaning_formatter_multi_char.md"
      temperature: 0.3