global:
  default_provider: "deepseek"
  max_daily_cost_usd: 10.0

providers:
  deepseek:
    api_key: "test-deepseek-key"

features:
  meaning_formatter:
    multi_char:
      provider: "deepseek"
      model: "deepseek-chat"
      prompt: "ai_config/prompts/meaning_formatter_multi_char.md"
      temperature: 0.3